### ISSUE TITLE
support Google App Engine's URL fetch service

### ISSUE THREAD

**Issue by djc** [djc/couchdb-python#147]
_From [acmo...@gmail.com](https://code.google.com/u/109155556562116051288/) on August 30, 2010 22:51:50_

What steps will reproduce the problem? 1. use Google's App Engine SDK
2. install couchdb-python into your new project
3. import couchdb
2. attempt to connect to an external couchdb server with couch = couchdb.Server(' https://couchdb.example.com/' )
3. exception is raised What is the expected output? What do you see instead? Google has their own url fetch service in their app engine. < https://code.google.com/appengine/docs/python/urlfetch/overview.html >. Other than that, they appear to prevent applications from making external socket connections. It appears to me that since this code uses couchdb/http.py, it won't work on Google's app engine. Here's the stacktrace:

Traceback (most recent call last):
  File "/home/amoore/dev/google_appengine/google/appengine/ext/webapp/**init**.py", line 511, in **call**
    handler.get(_groups)
  File "/home/amoore/dev/emradmin/main.py", line 13, in get
    userdb = couch['user']
  File "/home/amoore/dev/emradmin/lib/python2.5/site-packages/couchdb/client.py", line 137, in **getitem**
    db.resource.head() # actually make a request to the database
  File "/home/amoore/dev/emradmin/lib/python2.5/site-packages/couchdb/http.py", line 377, in head
    return self._request('HEAD', path, headers=headers, *_params)
  File "/home/amoore/dev/emradmin/lib/python2.5/site-packages/couchdb/http.py", line 419, in _request
    credentials=self.credentials)
  File "/home/amoore/dev/emradmin/lib/python2.5/site-packages/couchdb/http.py", line 239, in request
    resp = _try_request_with_retries(iter(self.retry_delays))
  File "/home/amoore/dev/emradmin/lib/python2.5/site-packages/couchdb/http.py", line 196, in _try_request_with_retries
    return _try_request()
  File "/home/amoore/dev/emradmin/lib/python2.5/site-packages/couchdb/http.py", line 211, in _try_request
    if conn.sock is None:
AttributeError: HTTPConnection instance has no attribute 'sock'

If urllib, urllib2 or httplib were used instead, I think this would work. What version of the product are you using? On what operating system? python 2.5.2, Google App Engine, linux

_Original issue: http://code.google.com/p/couchdb-python/issues/detail?id=147_

**Comment by vl4dt** [comment]
Hello, I don't know if this issue is still valid but I am having a similar issue only when trying to access a view's results, like this:

```python
def count_users(client_id, collection=COLLECTION_CLIENT):
    """Counts the users for a given client: <client_id>."""
    couch = couchdb.Server(COUCHDB_URL)

    db = couch[collection]

    view = db.view('client/users')

    results = view[client_id]

    return len(results.rows)
```

The error I get is the following (excerpt):
```python
  File "/base/data/home/apps/s~liu-passport-api-qa/1.390979779811766718/lib/couchdb/client.py", line 1196, in rows
    self._fetch()
  File "/base/data/home/apps/s~liu-passport-api-qa/1.390979779811766718/lib/couchdb/client.py", line 1182, in _fetch
    data = self.view._exec(self.options)
  File "/base/data/home/apps/s~liu-passport-api-qa/1.390979779811766718/lib/couchdb/client.py", line 1048, in _exec
    _, _, data = _call_viewlike(self.resource, options)
  File "/base/data/home/apps/s~liu-passport-api-qa/1.390979779811766718/lib/couchdb/client.py", line 1107, in _call_viewlike
    return resource.get_json(**_encode_view_options(options))
  File "/base/data/home/apps/s~liu-passport-api-qa/1.390979779811766718/lib/couchdb/http.py", line 510, in get_json
    return self._request_json('GET', path, headers=headers, **params)
  File "/base/data/home/apps/s~liu-passport-api-qa/1.390979779811766718/lib/couchdb/http.py", line 535, in _request_json
    data = json.decode(data.read().decode('utf-8'))
  File "/base/data/home/apps/s~liu-passport-api-qa/1.390979779811766718/lib/couchdb/http.py", line 153, in read
    self.close()
  File "/base/data/home/apps/s~liu-passport-api-qa/1.390979779811766718/lib/couchdb/http.py", line 162, in close
    self.resp.read(CHUNK_SIZE)
DeadlineExceededError: The overall deadline for responding to the HTTP request was exceeded.
```

I'd prefer not to query the database via urlfetch, is easy as well but, why bother? I just like the function as it is, simple, readable and clean :+1:

**Comment by djc** [comment]
I don't really have access to GAE, so I can't work on a fix. If you come up with a fix that is sufficiently low-complexity/well-contained, I wouldn't mind merging it.

**Comment by Philoozushi** [comment]
@vl4dt I just bumped into the same issue.
Did you get to fix it? Or have a clue about the problem and which part should be fixed?

**Comment by Philoozushi** [comment]
@vl4dt @djc it seems the problem described here is a duplicate of #224.
And alexan...@codjovi.fr pointed out the right problem : an infinite loop within `http:ResponseBody::close`. I'll continue on their issue.
