### ISSUE TITLE
couchdb-python does not work with couchbase sync gateway

### ISSUE THREAD

**Issue by hermitdemschoenenleben** [djc/couchdb-python#287]
When trying to connect to a couchbase sync gateway, I get the following error:

    from couchdb import Server

    couch = Server('http://192.168.2.103:4985')

    db = couch['messages']

      [ben@localhost daemon] $ python daemon.py 
      Traceback (most recent call last):
        File "daemon.py", line 5, in <module>
          db = couch['messages']
        File "/usr/lib/python2.7/site-packages/couchdb/client.py", line 142, in __getitem__
          db.resource.head() # actually make a request to the database
        File "/usr/lib/python2.7/site-packages/couchdb/http.py", line 528, in head
          return self._request('HEAD', path, headers=headers, **params)
        File "/usr/lib/python2.7/site-packages/couchdb/http.py", line 560, in _request
          credentials=self.credentials)
        File "/usr/lib/python2.7/site-packages/couchdb/http.py", line 357, in request
          num_redirects=num_redirects + 1)
        File "/usr/lib/python2.7/site-packages/couchdb/http.py", line 276, in request
          conn = self.connection_pool.get(url)
        File "/usr/lib/python2.7/site-packages/couchdb/http.py", line 486, in get
          conn.connect()
        File "/usr/lib64/python2.7/httplib.py", line 836, in connect
          self.timeout, self.source_address)
        File "/usr/lib64/python2.7/socket.py", line 557, in create_connection
          for res in getaddrinfo(host, port, 0, SOCK_STREAM):
      socket.error: [Errno 11] Resource temporarily unavailable

As fas as I understood, the reason for this is that at first request a redirect to a relative url ('/messages') is called, and the following request then fails because no host name was specified.

I fixed it by inserting this code into http.py after line 351, which adds a host name if none is given:

            location_split = util.urlsplit(location)

            if not location_split[0]:
                orig_url_split = util.urlsplit(url)
                location = util.urlunsplit(orig_url_split[:2] + location_split[2:])

**Comment by djc** [comment]
Thanks for reporting this issue. Would you be able to do a pull request with your proposed change?

**Comment by hermitdemschoenenleben** [comment]
I created one: https://github.com/djc/couchdb-python/pull/288

**Comment by djc** [comment]
Thanks!
